services:
  frontend:
    build:
      context: '../frontend/news-hack'
      dockerfile: ../../docker/Frontend.Dockerfile
    ports:
      - "5173:5173"
  backend:
    build:
      context: '../frontend/news-hack'
      dockerfile: ../../docker/Backend.Dockerfile
    ports:
      - "5001:5001"
