name: pre-commit

env:
  go_version: 1.23.3
  python_version: 3.12.7

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - name: Run pre-commit
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pre-commit
          pre-commit install
          pre-commit run --all-files
